# Generated by Django 5.2.11 on 2026-02-11 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='every_hours',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='schedule_type',
            field=models.CharField(choices=[('free_text', 'Free Text'), ('per_hour', 'Per Hour'), ('per_day', 'Per Day'), ('specific_times', 'Specific Times')], default='free_text', max_length=20),
        ),
        migrations.AddField(
            model_name='medication',
            name='take_bedtime',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medication',
            name='take_evening',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medication',
            name='take_morning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medication',
            name='take_noon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medication',
            name='take_with_breakfast',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medication',
            name='take_with_dinner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medication',
            name='take_with_lunch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medication',
            name='times_per_day',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
