# Generated by Django 5.2.11 on 2026-02-12 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0002_medication_every_hours_medication_schedule_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_action', models.CharField(choices=[('create', 'Created Diagnosis'), ('update', 'Updated Diagnosis'), ('approve', 'Approved Diagnosis')], default='update', max_length=20)),
                ('symptom_signature', models.TextField(blank=True)),
                ('ai_primary_diagnosis', models.CharField(blank=True, max_length=255)),
                ('doctor_final_diagnosis', models.CharField(blank=True, max_length=255)),
                ('ai_suggested_diagnoses', models.JSONField(blank=True, default=list)),
                ('ai_medications', models.JSONField(blank=True, default=list)),
                ('doctor_medications', models.JSONField(blank=True, default=list)),
                ('correction_flags', models.JSONField(blank=True, default=list)),
                ('correction_summary', models.TextField(blank=True)),
                ('feedback_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_entries', to='diagnosis.diagnosis')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
